AWSTemplateFormatVersion: '2010-09-09'
Description: Define Production S3 Bucket for File Sync

Parameters:
  ProductionBucketName:
    Type: String
    Default: resume.timjosmith.com
    Description: Name of the production S3 bucket

Resources:
  ProductionBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref ProductionBucketName
      Tags:
        - Key: Environment
          Value: Production


