AWSTemplateFormatVersion: '2010-09-09'
Description: Placeholder template for triggering pipeline

Parameters:
  DummyParameter:
    Type: String
    Default: DefaultValue
    Description: Placeholder parameter to allow stack updates

Resources: {}
