AWSTemplateFormatVersion: '2010-09-09'
Description: Placeholder template to force updates in the pipeline

Parameters:
  DummyParameter:
    Type: String
    Default: DefaultValue
    Description: Parameter to allow stack updates dynamically

Resources:
  PlaceholderTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: PlaceholderTopicForPipeline



