AWSTemplateFormatVersion: '2010-09-09'
Description: Sync S3 Staging Bucket to Prod Bucket

Parameters:
  DummyParameter:
    Type: String
    Default: DefaultValue
Resources:
  # Define the S3 Bucket for Staging
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: resume.staging.com
      Tags:
        - Key: LastUpdated
          Value: !Ref DummyParameter
      WebsiteConfiguration:
        IndexDocument: index.html

  # Trigger update

