name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy with CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: resumenominalbucket  # Stack name
          template: ./main.yml  # Path to your CloudFormation template
          capabilities: CAPABILITY_NAMED_IAM
          role-arn: arn:aws:iam::401907937551:role/OIDC_practice_cicd_pipeline  # IAM Role ARN
        env:
          AWS_DEFAULT_REGION: eu-west-2  # Set the AWS region as an environment variable
