name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Needed for OIDC authentication
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::401907937551:role/OIDC_practice_cicd_pipeline
          aws-region: eu-west-2  # Set your AWS region

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file ../../../main.yml \
            --stack-name resumenominalbucket \
            --capabilities CAPABILITY_NAMED_IAM
