name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Allows issuing an OIDC token
      contents: read   # Grants access to the repository contents
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::401907937551:role/OIDC_practice_cicd_pipeline
          aws-region: eu-west-2

      - name: Deploy with CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1.2.0
        with:
          name: 'resumenominalbucket'
          template: ./main.yml
          capabilities: CAPABILITY_NAMED_IAM
          parameters: |
            DummyParameter=$(date +%s)
