name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Allows issuing an OIDC token
      contents: read   # Grants access to the repository contents
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::401907937551:role/OIDC_practice_cicd_pipeline
          aws-region: eu-west-2

      - name: Deploy CloudFormation (placeholder)
        uses: aws-actions/aws-cloudformation-github-deploy@v1.2.0
        with:
          name: 'resume-placeholder-stack1'
          template: ./main.yml
          capabilities: CAPABILITY_NAMED_IAM
          parameter-overrides: |
            DummyParameter=$(date +%s)  # Allows triggering updates       

      - name: Debug AWS environment variables
        run: |
          echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID"
          echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY"
          echo "AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN"

      - name: Sync index.html from staging to production
        run: |
          python scripts/sync_s3.py
        env:
          AWS_DEFAULT_REGION: eu-west-2
          SOURCE_BUCKET: resume.staging.com
          DESTINATION_BUCKET: testbucket07732
          FILE_KEY: index.html

